services:
    notification-api:
      container_name: notification-api
      image: jonnattangc/notification-api:1.0.1
      build: .
      restart: none
      ports:
        - "8060:8060"
      volumes:
        - .:/home/jonnattan
      env_file:
        - ../envs/notification_api.env
      networks:
        - db-net
      #command: tail -f /home/jonnattan/app/main.py
networks:
  db-net:
